export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS : "SET_PRODUCTS",
    SET_DESC_PRODUCTS: "SET_DESC_PRODUCTS",
    REMOVE_DESC_PRODUCTS: "REMOVE_DESC_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCTS : "REMOVE_SELECTED_PRODUCTS",
    SIGNUP : "SIGNUP",
    LOGIN : "LOGIN",
    FETCH_PRODUCTS_CATEGORIES : "FETCH_PRODUCTS_CATEGORIES",
    SELECTED_PRODUCT_CATEGORY : "SELECTED_PRODUCT_CATEGORY",
    REMOVE_SELECTED_PRODUCT_CATEGORY : "REMOVE_SELECTED_PRODUCT_CATEGORY",
}